In [1]:
import os
import numpy as np
import pandas as pd

chrom = "/home/kgulbarg/thesis/INR_SCHIC/Nagano_Data/G1/G1_3/chr1.txt"

In [2]:
df = pd.read_csv(chrom, sep=r"\s+", header=0, comment="#")
    
arr = df[["bin1","bin2","count"]].to_numpy(int)

In [3]:
print(len(arr))

12676


In [4]:
for i in range(len(arr)):
    print(arr[i])

[129 130   1]
[159 162   2]
[84 84  1]
[135 135   1]
[57 57  1]
[192 192   1]
[194 194   1]
[121 121   1]
[108 108   1]
[19 19  1]
[40 40  1]
[145 145   1]
[70 70  1]
[ 74 121   1]
[134 134   1]
[195 195   1]
[ 77 107   1]
[176 176   1]
[75 92  1]
[91 91  1]
[38 38  3]
[164 164   1]
[43 74  1]
[195 195   3]
[82 83  3]
[192 192   1]
[52 52  1]
[196 196   1]
[41 70  1]
[145 145   1]
[22 22  1]
[ 9 25  1]
[ 6 33  1]
[125 125   1]
[94 94  2]
[184 184   1]
[172 172   1]
[131 163   1]
[171 174   2]
[110 117   1]
[71 71  1]
[69 69  1]
[103 118   1]
[35 35  3]
[15 31  2]
[28 28  1]
[159 159   1]
[91 92  1]
[79 79  2]
[17 17  2]
[142 142   1]
[136 136   1]
[21 21  1]
[191 192   2]
[77 77  1]
[120 134   2]
[193 195   1]
[177 177   2]
[67 67  1]
[78 78  1]
[82 82  1]
[192 192   1]
[62 62  3]
[120 120   1]
[148 148   1]
[167 168   2]
[87 88  1]
[31 31  1]
[108 122   1]
[52 52  2]
[35 35  1]
[91 91  1]
[21 21  2]
[78 78  1]
[68 69  1]
[164 167   1]
[137 137   1]
[149 149   1]
[23 23  1]
[128 128   

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
print(len(df))

12676


In [8]:
print(df)

       bin1  bin2  count
0       129   130      1
1       159   162      2
2        84    84      1
3       135   135      1
4        57    57      1
...     ...   ...    ...
12671    43    43      1
12672    41    76      1
12673    15    15      1
12674   195   195      1
12675   132   133      1

[12676 rows x 3 columns]


In [10]:
print(df['bin1'][2])

84


In [14]:
dupes = df.duplicated(keep=False)
print(dupes)

0         True
1        False
2         True
3         True
4         True
         ...  
12671     True
12672     True
12673     True
12674     True
12675     True
Length: 12676, dtype: bool


In [15]:
print("Number of duplicate rows:", dupes.sum())

Number of duplicate rows: 11388


In [12]:
dupes = df.duplicated(subset=["bin1", "bin2"], keep=False)
print(dupes)

0         True
1        False
2         True
3         True
4         True
         ...  
12671     True
12672     True
12673     True
12674     True
12675     True
Length: 12676, dtype: bool


In [13]:
print("Number of duplicate rows:", dupes.sum())

Number of duplicate rows: 11980


In [16]:
df_dupes = df.loc[dupes].sort_values(["bin1","bin2"])
print(df_dupes)

       bin1  bin2  count
119       3     3      1
646       3     3      1
746       3     3      1
1286      3     3      2
1291      3     3      1
...     ...   ...    ...
11294   196   196      1
11753   196   196      1
11758   196   196      1
11814   196   196      1
11860   196   196      1

[11388 rows x 3 columns]


In [18]:
df_agg = df.groupby(["bin1", "bin2"], as_index=False)["count"].sum()
print(df_agg)

      bin1  bin2  count
0        3     3     63
1        3     4     10
2        3     5      1
3        3     6      1
4        3     9      2
...    ...   ...    ...
1696   194   196      3
1697   195   195     77
1698   195   196     13
1699   196   196     75
1700   197   197      1

[1701 rows x 3 columns]


In [22]:
tmp = df[df["bin1"] != df["bin2"]].copy()  # ignore diagonal
tmp["min"] = np.minimum(tmp["bin1"], tmp["bin2"])
tmp["max"] = np.maximum(tmp["bin1"], tmp["bin2"])
tmp["ori"] = np.where(tmp["bin1"] < tmp["bin2"], "ij", "ji")

has_reversed = (tmp.groupby(["min", "max"])["ori"].nunique().eq(2)).any()
print("Reversed-order duplicates?", bool(has_reversed))
# if bool(has_reversed):
#     print("Reversed-order duplicates?", bool(has_reversed))

Reversed-order duplicates? False
